[book]
authors = ["Samuel Åkesson"]
language = "sv"
multilingual = false
src = "src"
title = "Mekatronik 1 | MTU"

[output.html]
mathjax-support = true
theme= "custom_theme"

# [preprocssor.last-changed]
# command = "mdbook-last-changed"
# renderer = ["html"]