[book]
authors = ["Samuel Åkesson"]
language = "sv"
multilingual = false
src = "src"
title = "Mekatronik 1 | MTU"
cname = "mek.samake.se"

[build]
build-dir = ".build"

[output.html]
mathjax-support = true
additional-css = ["theme/custom.css"]
preferred-dark-theme = "ayu"

[output.html.print]
enable = false

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
