services:
  mdbook:
#   image: ghcr.io/sermuns/mtu:latest
    build: .
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./book:/book
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /book
    entrypoint: "mdbook"
    command: "serve --hostname 0.0.0.0"
    stop_signal: SIGKILL
