services:
  mdbook:
    image: ghcr.io/sermuns/mtu:latest
    restart: unless-stopped
    container_name: mdbook
    user: 1000:1000
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./book:/book
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /book
    command: "mdbook serve --hostname 0.0.0.0"
    stop_signal: SIGKILL
