services:
  mdbook:
    build: .
    user: 1000:1000
    restart: unless-stopped
    network_mode: host
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: "mdbook"
    command: "serve --hostname 0.0.0.0"
    stop_signal: SIGKILL
