services:
  mdbook:
    user: 1000:1000
    container_name: mdbook
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/book
    working_dir: /book
    command: "mdbook serve --hostname 0.0.0.0"
    stop_grace_period: 1s
